# mainly for nvim/init.lua
column_width = 150
line_endings = "Unix"
indent_type = "Tabs"
indent_width = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
# collapse_simple_statement = "Never"
collapse_simple_statement = "Always"

[sort_requires]
enabled = false
