#! /usr/bin/env bash

cut_off='--------------------------------------------'
pacman_conf=/etc/pacman.conf

no_root () {
    if [[ $USER = 'root' ]]; then
        echo "Do not use root."
        exit -1
    fi
}

# $1 prompt
put_cutoff () {
    _line="\n${cut_off}\n"
    echo -e $_line
    if [[ -n "$1" ]]; then
        echo -e $1
        echo -e $_line
    fi
}

do_install () {
    sudo pacman -S --needed --noconfirm $*
}

display_array () {
    tmp_array=($@)
    length=${#tmp_array[@]}
    for (( i=0; i<$length; i++ )); do
        echo "$i    ${tmp_array[$i]}"
    done
    echo
}

check_input () {
    _range=$1
    is_valid=no
    _default=${_range:0:1}
    while [[ $is_valid = 'no' ]]; do
        read -p "Input: " ans
        [[ -z "$ans" ]] && ans=$_default
        ans=`echo $ans | tr '[A-Z]' '[a-z]'`
        if [[ "$_range" = *$ans* ]]; then
            is_valid=yes
        else
            echo "Valid answer: $_range (default=$_default):"
        fi
    done
}

# -----------------------------------------------------------------------------
# basic
# -----------------------------------------------------------------------------

enable_multilib() {
    sudo cat >>/etc/pacman.conf << EOF
[multilib]
Include = /etc/pacman.d/mirrorlist
EOF
}

check_multilib_support () {
    echo 'Check multilib support ...'
    if [[ -z "grep '^\[multilib\]' $pacman_conf" ]]; then
        multilib_enabled=0
        echo "Add multilib repo support? (Y/n)"
        check_input yn
        [[ $ans = 'y' ]] && enable_multilib && multilib_enabled=1
        sudo pacman -Sy
    else
        multilib_enabled=1
    fi

    (( $multilib_enabled == 0 )) && enable_multilib
    echo "Support multilib: $multilib_enabled"
}

