debug = true
paging = true
# pager_command = "more asdfsadga"
# pager_command = "more asdf"
pager_command = "less -F"

auto_clear = false
max_cached = 1000000
english_only = false
theme = "temp"
http_proxy = ""
freq_alert = true

[logging]
  enable = true
  path = ""
  level = "debug"
  stderr = false
